spring:
    datasource:
        url: jdbc:mysql://localhost:3306/yunquanlai?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: 123456
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    cache:
      ehcache:
        config: ehcache
wechat:
  miniapp:
    appid: wx39b1debf7c7b57f7
    secret: b82a5f7d5d654106447a28a2efeb9f73
#    token: 111
#    aesKey: 111
    msgDataFormat: JSON
  pay:
    appId: wx39b1debf7c7b57f7
    mchId: 1494681812
    mchKey: a9b80505a74e4c748daf576357b8f20a